### ISSUE TITLE
Multiples ingress alias

### ISSUE THREAD

**Issue by weyderfs** [SonarSource/helm-chart-sonarqube#101]
I'm trying to use more of one DNS name to without, success, Is it no possible use multiple names:

```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Ingress.spec.rules[0].host): invalid type for io.k8s.api.networking.v1.IngressRule.host: got "array", expected "string"
```
My _values.yaml_:

```
ingress:
  enabled: true
  # Used to create an Ingress record.
  hosts:
    - name: 
      - domain-a.test
      - domain-b.test
      # Different clouds or configurations might need /* as the default path
      path: /*
      # For additional control over serviceName and servicePort
      # serviceName: someService
      # servicePort: somePort
  annotations:
    kubernetes.io/ingress.class: istio
```
