### ISSUE TITLE
Plugin download fails for StatefulSet

### ISSUE THREAD

**Issue by haljoh** [SonarSource/helm-chart-sonarqube#114]
I have faced an issue when deploying the chart using the StatefulSet. The plugin init-container fails with permission errors when downloading plugins. I have managed to fix this by adding POD level securityContext into the stateful set template in the same way as it is already done in the deployment kind.

I have created a PR for this issue also [Fix plugin download issue for StatefulSet chart](https://github.com/SonarSource/helm-chart-sonarqube/pull/113)

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @haljoh ,

can you share a little more about the issue that you are facing? i am not able to reproduce this on a kind cluster. 
apart from that you can set the security context for the init container that is downloading the plugins [here](https://github.com/SonarSource/helm-chart-sonarqube/blob/master/charts/sonarqube/templates/sonarqube-sts.yaml#L236)

so a example `values.yaml` could look like this:

```yaml
plugins:
  install:
    - "https://github.com/sbaudoin/sonar-ansible/releases/download/v2.4.0/sonar-ansible-extras-plugin-2.4.0.jar"
    - "https://github.com/sbaudoin/sonar-yaml/releases/download/v1.5.2/sonar-yaml-plugin-1.5.2.jar" 
  lib: []

  # For use behind a corporate proxy when downloading plugins
  # httpProxy: ""
  # httpsProxy: ""
  # noProxy: ""

  # image: curlimages/curl:7.76.1
  # resources: {}

  # .netrc secret file with a key "netrc" to use basic auth while downloading plugins
  # netrcCreds: ""

  # Set to true to not validate the server's certificate to download plugin
  noCheckCertificate: false
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000

```

**Comment by haljoh** [comment]
Hello @tobias-trabelsi-sonarsource,

I have deployed SonarQube on Azure AKS, Kubernetes Version: 1.21.2. 

For storage provisioning I am using the Azure Disk CSI driver.

The values I have provided in the plugins section are:
```yaml
plugins:
    install:
      - "https://github.com/dependency-check/dependency-check-sonar-plugin/releases/download/2.0.8/sonar-dependency-check-plugin-2.0.8.jar"
      - "https://github.com/vaulttec/sonar-auth-oidc/releases/download/v2.0.0/sonar-auth-oidc-plugin-2.0.0.jar"
    lib: []

    # For use behind a corporate proxy when downloading plugins
    # httpProxy: ""
    # httpsProxy: ""
    # noProxy: ""

    # image: edudev.azurecr.io/tools/curl:7_79_1
    # resources: {}

    # .netrc secret file with a key "netrc" to use basic auth while downloading plugins
    # netrcCreds: ""

    # Set to true to not validate the server's certificate to download plugin
    noCheckCertificate: false
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
```

When I deploy with these values I get the following error in the plugin-init-container:
```
curl: (23) Failure writing output to destination
```

I added a `ls -la` command in the install_plugin.sh script to look at the permissions and I can see that the permission for the download folder still is root:
```
total 12
drwxr-xr-x    3 root     root          4096 Nov 10 12:54 .
drwxr-xr-x    4 root     root          4096 Nov 10 12:54 ..
drwxr-xr-x    2 root     root          4096 Nov 10 12:54 downloads
```

The init-fs init-container runs fine and changes the permissions to 1000 but for some reason the permissions are back to root when the install plugins init container starts. 

To solve this issue I added POD level security context into the sonarqube-sts.yaml file in the same way as you already have in the deployment.yaml file. 

```yaml
    spec:
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
      initContainers:
```

After that it started to work fine with above mentioned values for plugins and the group permission for the download folder is 1000

```
total 12
drwxr-xr-x    3 root     root          4096 Nov 10 13:07 .
drwxr-xr-x    4 root     root          4096 Nov 10 13:07 ..
drwxrwsr-x    2 root     1000          4096 Nov 10 13:07 downloads
```

I do not know if this is the correct solution for this issue but it works for me. Another question I have is why do you include the POD level security context for deployment kind and not for StatefulSet kind?

BR,
Johan
