### ISSUE TITLE
Failure in probes

### ISSUE THREAD

**Issue by cotvictor** [SonarSource/helm-chart-sonarqube#124]
Hi,

I am trying to install sonarqube chart on a cluster version 1.19.11, but my pod is always restarting. My setup is pretty simple, I am trying to install only sonar sts which is gonna connect to a Postgre instance from outside of the cluster. And I always get probes failures, tried to increase liveness probe, but of course it's not helping as I get connection refused in error message. From the pod itself I can't try to reach those urls `/api/system/liveness` as the container doesn't contains networking tools. 
Could you help me figure out what's wrong in my configs:

```
  values:
    securityContext:
      fsGroup: 1000
    containerSecurityContext:
      runAsUser: 999
    image:
      repository: sonarqube
      tag: 9.1.0-community
      pullPolicy: IfNotPresent
    ingress:
      enabled: true
      hosts:
        - name: sonarqube.platforminternal.online
          path: /
      tls:
        - secretName: tls-appservice-online
          hosts:
            - sonarqube.platforminternal.online
    persistence:
      enabled: true
      storageClass: default
      accessMode: ReadWriteOnce
      size: 5Gi
      uid: 1000
    postgresql:
      enabled: false
    jdbcOverwrite:
      enable: true
      # The JDBC url of the external DB
      jdbcUrl: "jdbc:postgresql://x.database.azure.com:5432/sonartest"
      # The DB user that should be used for the JDBC connection
      jdbcUsername: "admin@postgresql"
      # Use this if you don't mind the DB password getting stored in plain text within the values file
      jdbcPassword: "pass"
    livenessProbe:
      initialDelaySeconds: 120
      periodSeconds: 60
      failureThreshold: 10
      sonarWebContext: /
    readinessProbe:
      initialDelaySeconds: 120
      periodSeconds: 60
      failureThreshold: 10
      sonarWebContext: /
```

Error messages:
```
Startup probe failed: Get "http://10.244.0.238:9000/api/system/status": dial tcp 10.244.0.238:9000: connect: connection refused
Startup probe failed: Get "http://10.244.0.239:9000/api/system/status": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
Readiness probe failed:
Back-off restarting failed container
Liveness probe failed: HTTP probe failed with statuscode: 401
```
