### ISSUE TITLE
Change admin default creds

### ISSUE THREAD

**Issue by cotoman** [SonarSource/helm-chart-sonarqube#125]
Hello, this might not be the best place for asking such a question, I'm taking my chances here. 
Could you help me to understand where I can find default credentials with which I can login into Sonar. My understanding is that it should be something like admin/admin - unfortunately it doesn't works for me. Also I tried to change it with `account.adminPassword` and `currentAdminPassword` - which didn't worked either.

Bellow is my configuration:
```
  values:
    image:
      repository: sonarqube
      tag: 9.2.1-community
      pullPolicy: IfNotPresent
    monitoringPasscode: "admin"
    account:
      adminPassword: admin
      currentAdminPassword: admin
    postgresql:
      enabled: false
    jdbcOverwrite:
      enable: true
      jdbcUrl: "jdbc:postgresql://localhost:5432/sonardb"
      jdbcUsername: "user@db"
      jdbcPassword: "pass"
```
