### ISSUE TITLE
[sonarqube] Improvements for handling monitoringPasscode value

### ISSUE THREAD

**Issue by kchenye-bitgo** [SonarSource/helm-chart-sonarqube#139]
Hello,

I've encountered a few things that can be improved surrounding the use of `monitoringPasscode` value.

## Missing env var in deployment.yaml

We recently bumped our SonarQube helm chart to the latest version and encountered our SonarQube pod in `CrashLoopBackOff` due to `403` on liveness checks. Upon closer inspection, I noticed the following environment variable was missing from the `templates/deployment.yaml` spec:

```yaml
           # taken from templates/sonarqube-sts.yaml
            - name: SONAR_WEB_SYSTEMPASSCODE
              valueFrom:
                secretKeyRef:
                  name: {{ template "sonarqube.fullname" . }}-monitoring-passcode
                  key: SONAR_WEB_SYSTEMPASSCODE
```

#### Steps to reproduce:
deploy the sonarqube helm chart with version `1.2.5+179`

## Handle secret value better in livenessProbe

The deployment and statefulset manifests both template `.Values.monitoringPasscode` straight into the manifest as follows:

```yaml
# example taken from templates/deployment.yaml
livenessProbe:
  httpGet:
    scheme: HTTP
    path: {{ .Values.livenessProbe.sonarWebContext }}api/system/liveness
    port: http
  httpHeaders:
  - name: X-Sonar-Passcode
    value: {{ .Values.monitoringPasscode }}
initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
```

This isn't optimal as the value is treated as a secret in other places (like above). I would recommend defining exec commands instead so the environment variable can be used instead. For example:

```yaml
livenessProbe:
  exec:
    command:
    - bash
    - -c
    - wget
    - -qO-
    - --header="X-Sonar-Passcode:${SONAR_WEB_SYSTEMPASSCODE}"
    - http://localhost:{{ .Values.servce.internalPort }}{{ .Values.livenessProbe.sonarWebContext }}api/system/liveness
initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
```
