### ISSUE TITLE
AWS IAM Role to connect to RDS Postgress

### ISSUE THREAD

**Issue by govindarajvenkatesan** [SonarSource/helm-chart-sonarqube#155]
Is there a way we can connect Sonarqube to RDS Postgres using AWS IAM Role using helm chart values?

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @govindarajvenkatesan ,

if i read and understand you correctly you want to use a AWS IAM role token to connect sonarqube to a RDS database and yes that should be possible if you provide your token [[1](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.Connecting.Java.html#UsingWithRDS.IAMDBAuth.Connecting.Java.AuthToken.Connect)] as a jdbc password. The [jdbc overwrite](https://github.com/SonarSource/helm-chart-sonarqube/blob/master/charts/sonarqube/values.yaml#L360) section should help you here.
Please note that the creation of the token and general surrounding setup like secret rotation etc can not be handled by the chart.

**Comment by govindarajvenkatesan** [comment]
@tobias-trabelsi-sonarsource  Yes we are looking to use IAM role to connect to DB instead of using password

```
"arn:aws:iam::<account>:role/rds-access-sandbox_sonarqube",
```

So as per your comment above we can pass above ARN in jdbcPassword?

**Comment by tobias-trabelsi-sonarsource** [comment]
No you will need to provide a auth token as the jdbcPassword

**Comment by govindarajvenkatesan** [comment]
@tobias-trabelsi-sonarsource  Sure. Let me check on the same. 

Also when we tried to pass the override values to helm chart install, the chart seems to be picking up the default value. Can you guide what would be the right override settings to connect to Postgres DB?

```
gvenkatesan@WLUD21B20:/mnt/c/Users/106466/Scripts$ aws-vault exec 'gvenkatesan' -- helm get values sonarqube -n sonarqube
USER-SUPPLIED VALUES:
jdbcOverwrite:
  enable: false
  sonar.jdbc.password: <>
  sonar.jdbc.url: jdbc:postgresql://postgres-devxyz.us-east-1.rds.amazonaws.com/db_sandbox_sonarqube
  sonar.jdbc.username: admin

 #kubectl exec -it sonarqube-sonarqube-0 -n sonarqube -- env | grep jdbc
SONAR_JDBC_URL=jdbc:postgresql://sonarqube-postgresql:5432/sonarDB
gvenkatesan@WLUD21B20:/mnt/c/Users/106466/Scripts$
```

**Comment by tobias-trabelsi-sonarsource** [comment]
see the little `jdbcOverwrite.enable` flag there? you need to explicitly enable the jdbc overwrite and disable the postgresql that is shipped as a dependency of this chart

**Comment by govindarajvenkatesan** [comment]
@tobias-trabelsi-sonarsource 

This is how we are generating the db auth token using IAM role. What would be the best way to use this in helm chart? Please suggest. Thanks.

```
"export PGPASSWORD=$(aws rds generate-db-auth-token --hostname postgres-dev.xxx.us-east-1.rds.amazonaws.com --port 5432 --region us-east-1 --username db_sandbox_sonarqube")
```

**Comment by tobias-trabelsi-sonarsource** [comment]
this is a very philosophical question that i can not really answer. 

if you are managing secrets in your cluster already it might be a good idea to continue with that and reference it using `jdbcOverwrite.jdbcSecretName`. If this is a long living token and you just want to deploy SQ, you can set this token in `jdbcOverwrite.jdbcPassword` and it will be picked up.
Whenever you are rotating this token you will need to adjust both of them. If there is a secret provider in your cluster already doing this for you it might be better to use this one. if you are doing this all manually, then it does not matter and will be a manual operation anyway.

**Comment by govindarajvenkatesan** [comment]
@tobias-trabelsi-sonarsource  Does it supports an annotation like a snippet below

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: apitoken-server
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::<account>:role/rds-access-sandbox_sonarqube"
```

**Comment by govindarajvenkatesan** [comment]
We provision Postgres using IAM Roles for Service Accounts (IRSA)  and we wanted to make use of this to connect from sonarqube to Postgres.

**Comment by tobias-trabelsi-sonarsource** [comment]
okay i thought i already clarified that you need to provide something that can work with the default jdbc driver for postgresql. there is no additional logic provided by this chart or sonarqube that would allow you to rotate or inject something specific to AWS.

you can use token auth as explained before to authenticate against database and you will need to provide the credentials as jdbc username / password. how you do this is up to you

**Comment by govindarajvenkatesan** [comment]
@tobias-trabelsi-sonarsource  Was looking something like this --> https://github.com/SonarSource/helm-chart-sonarqube/blob/master/charts/sonarqube/values.yaml#L459

Is there any examples that SonarQube repo has?

**Comment by tobias-trabelsi-sonarsource** [comment]
nope

**Comment by govindarajvenkatesan** [comment]
@tobias-trabelsi-sonarsource  I have the below in upstream/values.yaml

```
  image:
    pullPolicy: "Always"
    tag: 9.2.4-community
  postgresql:
    enabled: false
  sonarProperties:
    sonar.core.serverBaseURL: "https://sonar-sandbox.dev.com"
    sonar.search.javaAdditionalOpts: "-Dlog4j2.formatMsgNoLookups=true" 
  jdbcOverwrite:
    enable: true
    jdbcUrl: "jdbc:postgresql://postgres-dev.xyz.us-east-1.rds.amazonaws.com/sandbox_sonarqube?socketTimeout=1500"
    jdbcUsername: xyzr"
    jdbcSecretName: "sonarqube-jdbc"
    jdbcSecretPasswordKey: "jdbc-password"
    ```
    
    While trying to locally render the template; don't see the  jdbcOverwrite values getting populated in the upstream.yaml. It's still getting all the default values. Thoughts?
    
    ```
    helm dependency update upstream
    helm template sonarqube upstream > resources/upstream.yaml
```

**Comment by tobias-trabelsi-sonarsource** [comment]
it seems like you are not referencing the values you provided. If i take your values and save them as `test.yaml` for example i can see that they are correctly propagated to the chart with

```
helm template -s templates/jdbc-config.yaml -f test.yaml sonarqube/sonarqube
```
=>
```
---
# Source: sonarqube/templates/jdbc-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-sonarqube-jdbc-config
  labels:
    app: sonarqube
    chart: sonarqube-1.2.5_179
    release: release-name
    heritage: Helm
data:
  SONAR_JDBC_USERNAME: "xyzr"
  SONAR_JDBC_URL: "jdbc:postgresql://postgres-dev.xyz.us-east-1.rds.amazonaws.com/sandbox_sonarqube?socketTimeout=1500"
```

**Comment by govindarajvenkatesan** [comment]
@tobias-trabelsi-sonarsource  So we have values.yaml under the folder upstream>values.yaml

The update-upstream.sh script pulls down the SonarQube helm chart, and templates it out to the resources/upstream.yaml file.
```
#!/usr/bin/env sh

helm dependency update upstream
helm template sonarqube upstream > resources/upstream.yaml
```

So how can we get all the templates and populate with overrides in values.yaml without passing those -f values.yaml file?

**Comment by tobias-trabelsi-sonarsource** [comment]
what about
``` bash
helm template -f upstream/values.yaml sonarqube upstream > resources/upstream.yaml
``` 
if this is not an option, you can try to tinker around with `-set` as documented [here](https://helm.sh/docs/intro/using_helm/#customizing-the-chart-before-installing).

on a side-note: ArgoCD can work with helm repositories directly. There is no need for this kind of scripting. a `Chart.yaml` that references the original helm chart and correctly scoped values are enough:

Chart.yaml
```yaml
apiVersion: v2
name: sonarqube
description: sonarqube
type: application

version: 0.1.0
appVersion: "9.2.4"

dependencies:
- name: sonarqube
  version: "1.2.5_179"
  repository: https://SonarSource.github.io/helm-chart-sonarqube
```

values.yaml
```yaml
sonarqube:
  image:
    pullPolicy: "Always"
    tag: 9.2.4-community
  postgresql:
    enabled: false
  sonarProperties:
    sonar.core.serverBaseURL: "https://sonar-sandbox.dev.com"
    sonar.search.javaAdditionalOpts: "-Dlog4j2.formatMsgNoLookups=true"
  jdbcOverwrite:
    enable: true
    jdbcUrl: "jdbc:postgresql://postgres-dev.xyz.us-east-1.rds.amazonaws.com/sandbox_sonarqube?socketTimeout=1500"
    jdbcUsername: "xyzr"
    jdbcSecretName: "sonarqube-jdbc"
    jdbcSecretPasswordKey: "jdbc-password"
```

**Comment by govindarajvenkatesan** [comment]
@tobias-trabelsi-sonarsource Tried that as well; but still getting the default templates getting rendered. 

![image](https://user-images.githubusercontent.com/91967175/151557107-fefd26b8-842e-4bf3-9f18-73cc830ed4f5.png)


![image](https://user-images.githubusercontent.com/91967175/151557161-cf312f06-a704-4938-a274-7989e65348a3.png)


![image](https://user-images.githubusercontent.com/91967175/151557219-65d51a59-561d-4fed-b48d-dd699d066b31.png)

**Comment by tobias-trabelsi-sonarsource** [comment]
Uhm this is not the chart in this repo. what repo do you have configured for upstream. could it be the one from oteemo by any chance?

**Comment by govindarajvenkatesan** [comment]
@tobias-trabelsi-sonarsource Here is the Chart.yaml file values

![image](https://user-images.githubusercontent.com/91967175/151560023-ea892b91-d63a-4364-aeb0-a98a2b28fcec.png)

**Comment by tobias-trabelsi-sonarsource** [comment]
the version you specify there is not known. can you give me the exact version of the chart you are using? we never released a chart with the chart version 9.2.4
latest sonarqube chart as of now is version `1.2.5+179`

**Comment by govindarajvenkatesan** [comment]
@tobias-trabelsi-sonarsource Made this change and see the below

![image](https://user-images.githubusercontent.com/91967175/151564177-39978b79-44b6-436c-a1b3-709f8912e6fb.png)


![image](https://user-images.githubusercontent.com/91967175/151564143-441529a8-6f65-46f3-8f68-c1bb6677e90a.png)


![image](https://user-images.githubusercontent.com/91967175/151564216-df2b53b4-e682-4b51-837b-30b836aab928.png)

**Comment by tobias-trabelsi-sonarsource** [comment]
Okay this is looking like the right chart now at least. Still the values that you showed me are not picked up, so i guess there is still a scoping issue. did you already try to set the values in the correct scope (might be `sonarqube` or `sonarqube-upstream`... i am a bit confused by this kind of setup)?

**Comment by govindarajvenkatesan** [comment]
@tobias-trabelsi-sonarsource  How do we disable this pod? What values should we be passing to disable this? Thanks

https://github.com/SonarSource/helm-chart-sonarqube/blob/master/charts/sonarqube/templates/tests/sonarqube-test.yaml#L1

**Comment by govindarajvenkatesan** [comment]
@tobias-trabelsi-sonarsource  NM. Found it --> https://github.com/SonarSource/helm-chart-sonarqube/blob/master/charts/sonarqube/values.yaml#L451. THanks

**Comment by govindarajvenkatesan** [comment]
@tobias-trabelsi-sonarsource What would be the stable docker taag that we can for 9.2.4? Will this be right?

```
tag: 9.2.4
```

**Comment by govindarajvenkatesan** [comment]
@tobias-trabelsi-sonarsource  Where can we find the release notes for 9.2.4? --> https://github.com/SonarSource/docker-sonarqube/releases/tag/9.2.4

**Comment by govindarajvenkatesan** [comment]
@tobias-trabelsi-sonarsource  Also can you let us know what is this used for - SONAR_WEB_SYSTEMPASSCODE ? 
Is this needed and anyway we can securely store this password?

```
---
# Source: sonarqube-upstream/charts/sonarqube/templates/secret.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-sonarqube-monitoring-passcode
  labels:
    app: sonarqube
    chart: sonarqube-1.2.5_179
    release: sonarqube
    heritage: Helm
type: Opaque
data:
  SONAR_WEB_SYSTEMPASSCODE: "xxxxx"
  ```
