### ISSUE TITLE
Postgresql password stored in plaintext in values.yaml

### ISSUE THREAD

**Issue by mtcolman** [SonarSource/helm-chart-sonarqube#169]
**Describe the bug**
Should the storing of a DB password in plaintext be considered a security risk? Would it not be better to pass it in via a secret?

**Versions used:**
- Chart Version: 2.0.0
- SonarQube Version: 9.3.0
- Helm Version: N/A
- Kubernetes Version: N/A

**values.yaml key in question:**
```yaml
postgresql:
  ...
  postgresqlPassword: "sonarPass"
```

**Additional context**
I'm wondering if this functionality is offered in the `jdbcOverwrite` section, however I'm not trying to provide an external database...?

**jdbcOverwrite section in values.yaml:**
```
## Override JDBC values
## for external Databases
jdbcOverwrite:
  enable: false
  # The JDBC url of the external DB
  jdbcUrl: "jdbc:postgresql://myPostgress/myDatabase?socketTimeout=1500"
  # The DB user that should be used for the JDBC connection
  jdbcUsername: "sonarUser"
  # Use this if you don't mind the DB password getting stored in plain text within the values file
  jdbcPassword: "sonarPass"
  ## Alternatively, use a pre-existing k8s secret containing the DB password
  # jdbcSecretName: "sonarqube-jdbc"
  ## and the secretValueKey of the password found within that secret
  # jdbcSecretPasswordKey: "jdbc-password"
```
