### ISSUE TITLE
BAD and POOR liveness probe security

### ISSUE THREAD

**Issue by felix-dpg** [SonarSource/helm-chart-sonarqube#200]
**Describe the bug**
There is a secret defined for systempasscode web api access, however in the liveness probe the password is in clear text. 
**Need to change this to an scripting liveness probe**, using the env variable SONAR_WEB_SYSTEMPASSCODE defined in the statefulset definition.

```
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /api/system/liveness
              port: http
              httpHeaders:
                - name: X-Sonar-Passcode
                  value: define_it

```
