### ISSUE TITLE
LTS: Install plugins fails with "Permission denied"

### ISSUE THREAD

**Issue by sebbes** [SonarSource/helm-chart-sonarqube#208]
When I add a plugin then the `install-plugins` init cotainer fails with `/tmp/scripts/install_plugins.sh: line 3: can't create /opt/sonarqube/extensions/downloads/list: Permission denied`. I played with the securityContext settings, but when I change the `securityContext` in the `plugins:` section to `0:0` then the `sonarqube-lts` container fails when executing this line: `rm /opt/sonarqube/extensions/downloads/list`

**Versions used:**
- Chart Version: 1.0.26+289
- SonarQube Version: 8.9.7
- Helm Version: 3.8.1
- Kubernetes Version:1.21

**Custom Values**
```yaml
plugins:
  install:
    - "https://github.com/dependency-check/dependency-check-sonar-plugin/releases/download/3.0.0/sonar-dependency-check-plugin-3.0.0.jar"
```

Am I doing anything wrong? 

By the way, the latest Chart from the sonarqube (non-LTS) works fine.
