### ISSUE TITLE
automountServiceAccountToken forced to false

### ISSUE THREAD

**Issue by david972** [SonarSource/helm-chart-sonarqube#220]
**Describe the bug**
I'm using vault to inject the PostgreSQL password and to do that I grant the service account to get its password.
But as the service account created by the chart force the field automountServiceAccountToken to false i getting this error
```
time="2022-05-22T17:08:31Z" level=error msg="failed to read login data" app=vault-env err="open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory" type=jwt
```

**Versions used:**
- Chart Version: 3.0.0+296
- SonarQube Version: 9.4.0
- Helm Version: v3.8.0
- Kubernetes Version: v1.23.5

**Custom Values**
Please add a minimal value example to reproduce this error
```yaml
annotations:
  vault.security.banzaicloud.io/vault-addr: http://vault.vault:8200
  vault.security.banzaicloud.io/vault-role: sqube-sonarqube
  vault.security.banzaicloud.io/vault-skip-verify: "true"
env:
  - name: SONAR_JDBC_PASSWORD
    value: vault:infra/data/sonar/database#password
```

**Expected behavior**
It would be preferable to be able to manage this field through the values

**Screenshots**
N/A
**Additional context**
N/A
