### ISSUE TITLE
Can't launch SonarQube with plugins

### ISSUE THREAD

**Issue by yanis-incepto** [SonarSource/helm-chart-sonarqube#222]
**Describe the bug**
Hello,
When I try to integrate plugins installation within the configuration files, the Sonarqube can't more be launched with the helmfile apply command (it infinitely reboots and displays a 503 error). I've got the bug with standard and LTS versions.

**Versions used:**
- Chart Version: 3.0.0 and 1.0.26
- SonarQube Version: those included on the charts, i haven't touched it
- Helm Version: 3.8.2
- Kubernetes Version: 1.21

**Custom Values**
Please add a minimal value example to reproduce this error
```yaml
#Help page : https://github.com/SonarSource/helm-chart-sonarqube/tree/master/charts/sonarqube
ingress:
  enabled: false
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "8m"
  hosts:
    - name: url
      path: "/"
  tls:
  - hosts:
    - url
    secretName: url
plugins:
  install:
    - "https://github.com/elegoff/sonar-rust/releases/download/v0.0.9/community-rust-plugin-0.0.9.jar"
    - "https://github.com/mc1arke/sonarqube-community-branch-plugin/releases/download/1.11.0/sonarqube-community-branch-plugin-1.11.0.jar"
sonarProperties:
  sonar.web.javaAdditionalOpts: "-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.11.0.jar=web"
  sonar.ce.javaAdditionalOpts: "-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.11.0.jar=ce"
account:
  adminPassword: secretpassword
  currentAdminPassword: secretpassword
```

**Expected behavior**
I'd like to use the two plugins I added on my values.yaml file.

**Screenshots**

**Additional context**
