### ISSUE TITLE
Problem to install plugins with LTS version

### ISSUE THREAD

**Issue by yanis-incepto** [SonarSource/helm-chart-sonarqube#224]
**Describe the bug**

**Versions used: **

    Chart Version: 1.0.26
    SonarQube Version: those included on the charts, i haven't touched it
    Helm Version: 3.8.2
    Kubernetes Version: 1.21

**Custom Values**
Please add a minimal value example to reproduce this error
```yaml
#Help page : https://github.com/SonarSource/helm-chart-sonarqube/tree/master/charts/sonarqube
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "8m"
  hosts:
    - name: host
      path: "/"
  tls:
  - hosts:
    - host
    secretName: host
#sonarSecretProperties:
#  sonarSecretKey: ""
plugins:
  install:
    - "https://github.com/elegoff/sonar-rust/releases/download/v0.0.9/community-rust-plugin-0.0.9.jar"
    - "https://github.com/mc1arke/sonarqube-community-branch-plugin/releases/download/1.11.0/sonarqube-community-branch-plugin-1.11.0.jar"
sonarProperties:
  jvmOpts: "-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.11.0.jar=web"
  jvmCeOpts: "-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.11.0.jar=ce"
account:
  adminPassword: secretpasswordtest
  currentAdminPassword: admin
```

**Expected behavior**
I tried to install plugins on LTS version but it has no effect : when I launch SonarQube, it haven't been installed.

**Screenshots**

**Additional context**
