### ISSUE TITLE
networkPolicy.additionalNetworkPolicys in values.yaml doesn't work properly

### ISSUE THREAD

**Issue by Mustaavalkosta** [SonarSource/helm-chart-sonarqube#227]
**Describe the bug**

Setting networkPolicy.additionalNetworkPolicys in values.yaml doesn't work.

```
$ helm upgrade --install -n sonarqube -f values.yaml sonarqube sonarqube/sonarqube

Error: UPGRADE FAILED: YAML parse error on sonarqube/templates/networkpolicy.yaml: error converting YAML to JSON: yaml: line 42: mapping values are not allowed in this context
```

Indent is set to 4 in [templates/networkpolicy.yaml](https://github.com/SonarSource/helm-chart-sonarqube/blob/master/charts/sonarqube/templates/networkpolicy.yaml#L112). Should it be 2 to be valid YAML for [NetworkPolicy](https://kubernetes.io/docs/concepts/services-networking/network-policies/)?

Fixing only that indent doesn't fix the issue though but with these additional changes to the template I'm able to get working NetworkPolicy which doesn't overwrite the default ones due to using same name for the NetworkPolicy resource:

```diff
diff --git a/charts/sonarqube/templates/networkpolicy.yaml b/charts/sonarqube/templates/networkpolicy.yaml
index 95a7c13..16b11a4 100644
--- a/charts/sonarqube/templates/networkpolicy.yaml
+++ b/charts/sonarqube/templates/networkpolicy.yaml
@@ -96,12 +96,12 @@ spec:
           protocol: UDP
 {{- end }}

-{{- if and .Values.networkPolicy.enabled .Values.networkPolicy.additionalNetworkPolicys -}}
+{{- if and .Values.networkPolicy.enabled .Values.networkPolicy.additionalNetworkPolicys }}
 ---
 kind: NetworkPolicy
 apiVersion: networking.k8s.io/v1
 metadata:
-  name: {{ template "sonarqube.fullname" . }}-network-policy
+  name: {{ template "sonarqube.fullname" . }}-additional-network-policy
   labels:
     app: {{ template "sonarqube.name" . }}
     chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
@@ -109,6 +109,6 @@ metadata:
     heritage: {{ .Release.Service }}
 spec:
 {{- with .Values.networkPolicy.additionalNetworkPolicys -}}
-{{ toYaml . | indent 4 }}
+{{ toYaml . | nindent 2 }}
 {{- end }}
{{- end -}}
```

An example of setting additional network policies in values.yaml documentation would also improve usability of the chart.

**Versions used:**
- Chart Version: 3.0.0+296
- SonarQube Version: 9.4.0
- Helm Version: 3.8.1
- Kubernetes Version: OpenShift 4.9.31 / Kubernetes v1.22.8

**Custom Values**
Please add a minimal value example to reproduce this error
```yaml
networkPolicy:
  enabled: true
  additionalNetworkPolicys:
    podSelector:
      matchLabels:
        app: sonarqube
    ingress:
    - ports:
      - protocol: TCP
        port: 9000
      from:
      - namespaceSelector:
          matchLabels:
            network.openshift.io/policy-group: ingress
    policyTypes:
    - Ingress
```

**Expected behavior**
Additional network policies to be created without overwriting the default ones.

**Screenshots**
None.

**Additional context**
Setting additional network policies is required for OpenShift route to work.

https://docs.openshift.com/container-platform/4.9/networking/network_policy/about-network-policy.html
