### ISSUE TITLE
please add -k option in prometheusExporter init container's cmd

### ISSUE THREAD

**Issue by Hokwang** [SonarSource/helm-chart-sonarqube#33]
Hi,

I use below code.
```
prometheusExporter:
  version: "0.15.0"
  httpProxy: <company-proxy server>
  httpsProxy: <company-proxy server>
```

But, here's a problem.
In 
https://github.com/SonarSource/helm-chart-sonarqube/blob/af0ae8e5ea1bc7d635a048c1507556948c1a0fe0/charts/sonarqube/templates/sonarqube-sts.yaml#L111

there's no `-k` option so I got ssl cert error. 

so please add -k option force
or you can provide `noCheckCertificate: true` like in `plugins:`
