### ISSUE TITLE
Installation on OpenShift 4.x fails with "Privileged containers are not allowed"

### ISSUE THREAD

**Issue by gasgithub** [SonarSource/helm-chart-sonarqube#44]
Trying to deploy SonarQube to OpenShift 4.6 via this helm chart.
I changed the following fields in values.yaml:

```
OpenShift:
  enabled: true

  securityContext:
    # For standard Kubernetes deployment, set enabled=true
    # If using OpenShift, enabled=false for restricted SCC and enabled=true for anyuid/nonroot SCC
    enabled: false

  volumePermissions:
    # For standard Kubernetes deployment, set enabled=false
    # For OpenShift, set enabled=true and ensure to set volumepermissions.securitycontext.runAsUser below.
    enabled: true
    # if using restricted SCC set runAsUser: "auto" and if running under anyuid/nonroot SCC - runAsUser needs to match runAsUser above
    securityContext:
      runAsUser: "auto"

```

Helm chart installs but sonarqube pod fails with the following message:

```
create Pod sonarqube-sonarqube-0 in StatefulSet sonarqube-sonarqube failed error: pods "sonarqube-sonarqube-0"
 is forbidden: unable to validate against any security context constraint: [spec.initContainers[1].securityContext.privileged: Invalid
 value: true: Privileged containers are not allowed spec.initContainers[2].securityContext.runAsUser: Invalid value: 0: must
 be in the ranges: [1000800000, 1000809999] spec.containers[0].securityContext.runAsUser: Invalid value: 1000: must
 be in the ranges: [1000800000, 1000809999]]
```

So either these settings are incorrect or helm is not installing correctly.

Regards
Gas
