### ISSUE TITLE
Compute Engine Java Opts cannot be overridden when using a custom certificate

### ISSUE THREAD

**Issue by mikeycmccarthy** [SonarSource/helm-chart-sonarqube#7]
If you provide a value for caCerts, then [this line](https://github.com/SonarSource/helm-chart-sonarqube/blob/master/charts/sonarqube/templates/deployment.yaml#L210-L213) in the template for the deployment will set your Compute Engine Java options as an environment variable.

I believe these win over the variables set in sonar.properties, and therefore you're stuck with the default settings if you want to use custom certs.

The Web options do not have this limitation  - see [here](https://github.com/SonarSource/helm-chart-sonarqube/blob/master/charts/sonarqube/templates/deployment.yaml#L204-L209). With this approach the additional arguments you provide as 'javaOpts' get added on to the end of the environment variable.

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @mikeycmccarthy ,

Can you explain why you need to add custom certificates to the compute engine? also it seems like you already have a solution in mind. do you want to create a PR for this?

**Comment by mikeycmccarthy** [comment]
Hi

I don't think we really do want to add custom certificates to the compute engine but the way the template is done means setting the custom certificates applies to both compute and web:

```yaml
env:
            - name: SONAR_WEB_JAVAOPTS
              {{- if .Values.caCerts }}
              value: {{ printf "-Djavax.net.ssl.trustStore=%s/certs/cacerts %s" .Values.sonarqubeFolder .Values.jvmOpts | trim | quote }}
              {{- else }}
              value: "{{ .Values.jvmOpts }}"
              {{- end }}
            {{- if .Values.caCerts }}
            - name: SONAR_CE_JAVAOPTS
              value: {{ printf "-Djavax.net.ssl.trustStore=%s/certs/cacerts" .Values.sonarqubeFolder | trim | quote }}
            {{- end }}
```

Setting caCerts in values also affects the CE environment variables.

I've created this issue here but at the moment we're using the Oteemo chart so I don't have a great way of being able to test this to make me confident in a PR at this point unfortunately.

I believe that jvmOpts is actually specific to Web and you'd need a different variable for Compute Engine, assuming you'd want to add custom certs onto Compute Engine at all. If you didn't I think potentially you could avoid setting it via an environment variable altogether and just use the conf approach (which I can confirm does set the entry in the conf file, it just gets ignored in favour of the environment variable)
