### ISSUE TITLE
No proxy when installing in aks

### ISSUE THREAD

**Issue by mnunezdm** [SonarSource/helm-chart-sonarqube#90]
Hello!

I'm trying to deploy sonarqube using helm in an aks.

I have tried activating the nginx & ingress using the values.yaml but I cannot see the service up.

```yaml
nginx:
  enabled: true

ingress:
  enabled: true
  # Used to create an Ingress record.
  hosts:
    - name: sonarqube.mnunezdm.com
      # Different clouds or configurations might need /* as the default path
      path: /*
      # For additional control over serviceName and servicePort
      # serviceName: someService
      # servicePort: somePort
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  # This property allows for reports up to a certain size to be uploaded to SonarQube
  # nginx.ingress.kubernetes.io/proxy-body-size: "8m"

  # Set ingressClassName if kubernetes version is >= 1.18
  # Reference: https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/
  ingressClassName: nginx
```

This is the output of the services in the sonarqube namespace

```bash
$ kubectl get services -n sonarqube
NAME                            TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
sonarqube-postgresql            ClusterIP   10.0.84.88     <none>        5432/TCP   3d21h
sonarqube-postgresql-headless   ClusterIP   None           <none>        5432/TCP   3d21h
sonarqube-sonarqube             ClusterIP   10.0.124.109   <none>        9000/TCP   3d21h
```
