### ISSUE TITLE
[Monitoring] - Prometheus Exporter isn't work

### ISSUE THREAD

**Issue by weyderfs** [SonarSource/helm-chart-sonarqube#93]
Guys,
I'm using the `prometheusExporter: enable: true` but the container `inject-prometheus-exporter` is got _connection refused_, by the way if I set to false the P. Exporter Sonar works fine.

Log of container `injection`:
```
*   Trying 199.232.64.209:443...
* connect to 199.232.64.209 port 443 failed: Connection refused
* Failed to connect to repo1.maven.org port 443: Connection refused
* Closing connection 0
*   Trying 199.232.64.209:443...
* connect to 199.232.64.209 port 443 failed: Connection refused
* Failed to connect to repo1.maven.org port 443: Connection refused
* Closing connection 0
```
Anyone can help?

The part of my YAML configuration:
```
prometheusExporter:
  enabled: true
  # jmx_prometheus_javaagent version to download from Maven Central
  version: "0.16.0"
  # Alternative full download URL for the jmx_prometheus_javaagent.jar (overrides prometheusExporter.version)
  # downloadURL: ""
  # if you need to ignore TLS certificates for whatever reason enable the following flag
  noCheckCertificate: false

  # Ports for the jmx prometheus agent to export metrics at
  webBeanPort: 8000
  ceBeanPort: 8001

  config:
    rules:
      - pattern: ".*"
  # Overrides config for the CE process Prometheus exporter (by default, the same rules are used for both the Web and CE processes).
  # ceConfig:
  #   rules:
  #     - pattern: ".*"
  # image: curlimages/curl:7.76.1
  # For use behind a corporate proxy when downloading prometheus
  # httpProxy: ""
  # httpsProxy: ""
  # noProxy: ""
  # Setting the security context to root as the /data volume is owned by root at this stage
  securityContext:
    runAsUser: 0
    runAsGroup: 0

# List of plugins to install.
# For example:
# plugins:
#  install:
#    - "https://github.com/AmadeusITGroup/sonar-stash/releases/download/1.3.0/sonar-stash-plugin-1.3.0.jar"
#    - "https://github.com/SonarSource/sonar-ldap/releases/download/2.2-RC3/sonar-ldap-plugin-2.2.0.601.jar"
plugins:
  install: []
  lib: []

  # For use behind a corporate proxy when downloading plugins
  # httpProxy: ""
  # httpsProxy: ""
  # noProxy: ""

  # image: curlimages/curl:7.76.1
  # resources: {}

  # .netrc secret file with a key "netrc" to use basic auth while downloading plugins
  # netrcCreds: ""

  # Set to true to not validate the server's certificate to download plugin
  noCheckCertificate: false
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000

## Values to add to SONARQUBE_WEB_JVM_OPTS
##
# jvmOpts: "-Djava.net.preferIPv4Stack=true"
jvmOpts: ""

## Values to add to SONAR_CE_JAVAOPTS
jvmCeOpts: ""

## a monitoring passcode needs to be defined in order to get reasonable probe results
# not setting the monitoring passcode will result in a deployment that will never be ready
monitoringPasscode: "define_it"
```

I've tried resolv the `repo1.maven.org` in the sonar container and returns this error:
```
bash-5.1$ wget https://repo1.maven.org
Connecting to repo1.maven.org (199.232.64.209:443)
wget: server returned error: HTTP/1.1 403 Forbidden
bash-5.1$ wget https://repo1.maven.org
```

Anyone can help me?
